# mybatis
spring:
  datasource:
    username: root
    password: 1437444656
    url: jdbc:mysql://localhost:3306/vote?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.vote.mapper: debug

mybatis:
  type-aliases-package: com.vote.pojo

pagehelper:
  helper-dialect: mysql
